services:

#  updater:
#    build: ./updater
#    container_name: dados_updater
#    volumes:
#      - ./dados_medianas_var:/data
#    command: ["python", "update.py"]
#    profiles: ["update"]

  app:
    build: ./app
    container_name: dados_app
    ports:
      - "8501:8501"
    volumes:
      - ./dados_medianas_var:/data
    command: ["streamlit", "run", "app.py", "--server.port=8501"]
    profiles: ["run"]
